// Source: docs/07-platform-operations/02-system-ownership.md
//         docs/07-platform-operations/01-team-roles.md
export const DOC_OWNERS: Record<string, string[]> = {
  'docs/00-system/00-system-overview.md': ['Nikhil Salunke'],
  'docs/00-system/01-three-brain-architecture.md': ['Nikhil Salunke', 'Pranav Nandeshwar'],
  'docs/00-system/04-current-platform-inventory.md': ['Nikhil Salunke'],
  'docs/01-foundations/00-company-thesis.md': ['Nikhil Salunke'],
  'docs/01-foundations/01-persona-ecosystem.md': ['Rohit Pandey', 'Gautami Kamath', 'Sanskriti Choudante'],
  'docs/01-foundations/03-product-blueprint.md': ['Nikhil Salunke', 'Aboli Mundralkar', 'Pragati Dhumal'],
  'docs/01-foundations/04-intelligence-model.md': ['Nikhil Salunke', 'Pranav Nandeshwar'],
  'docs/01-foundations/05-behavior-system.md': ['Sanskriti Choudante', 'Utkarsha Chougule'],
  'docs/01-foundations/06-trust-determinism-model.md': ['Nikhil Salunke', 'Pranav Nandeshwar', 'Utkarsha Chougule'],
  'docs/01-foundations/07-growth-intelligence-model.md': ['Gautami Kamath', 'Sanskriti Choudante'],
  'docs/02-platform-architecture/00-platform-architecture-overview.md': ['Nikhil Salunke', 'Tushar Patil'],
  'docs/02-platform-architecture/04-deterministic-brain-architecture.md': ['Nikhil Salunke', 'Pranav Nandeshwar'],
  'docs/02-platform-architecture/05-user-brain-architecture.md': ['Sanskriti Choudante', 'Utkarsha Chougule'],
  'docs/02-platform-architecture/10-frontend-architecture.md': ['Aboli Mundralkar', 'Pragati Dhumal', 'Tushar Patil'],
  'docs/02-platform-architecture/11-backend-architecture.md': ['Tushar Patil', 'Vaishnavi Dhawale'],
  'docs/02-platform-architecture/12-database-architecture.md': ['Vaishnavi Dhawale'],
  'docs/03-intelligence-systems/00-intelligence-systems-overview.md': ['Nikhil Salunke', 'Pranav Nandeshwar'],
  'docs/03-intelligence-systems/04-intelligence-models.md': ['Nikhil Salunke', 'Pranav Nandeshwar'],
  'docs/03-intelligence-systems/10-deterministic-engine.md': ['Nikhil Salunke', 'Pranav Nandeshwar'],
  'docs/03-intelligence-systems/12-user-intelligence.md': ['Sanskriti Choudante', 'Utkarsha Chougule'],
  'docs/05-growth-systems/00-growth-systems-overview.md': ['Ajay Landge', 'Rohit Pandey', 'Gautami Kamath'],
  'docs/05-growth-systems/01-content-engine.md': ['Shubham Kamble', 'Krishna Sable'],
  'docs/05-growth-systems/03-seo-architecture.md': ['Ajay Landge', 'Rohit Pandey', 'Krishna Sable'],
  'docs/05-growth-systems/04-llm-discovery.md': ['Ajay Landge', 'Pranav Nandeshwar'],
  'docs/05-growth-systems/05-crm-integration.md': ['Gautami Kamath'],
  'docs/06-data-systems/00-dataset-ingestion-map.md': ['Riya Wankhade', 'Ruchita Vitkar'],
  'docs/06-data-systems/02-data-pipeline-architecture.md': ['Riya Wankhade', 'Pranav Nandeshwar'],
  'docs/06-data-systems/03-deterministic-validation.md': ['Ruchita Vitkar', 'Riya Wankhade'],
  'docs/06-data-systems/04-audit-and-logging.md': ['Ruchita Vitkar'],
  'docs/07-platform-operations/01-team-roles.md': ['Nikhil Salunke'],
  'docs/07-platform-operations/02-system-ownership.md': ['Nikhil Salunke', 'Vaishnavi Dhawale', 'Ruchita Vitkar', 'Riya Wankhade'],
  'docs/07-platform-operations/07-development-workflow.md': ['Nikhil Salunke', 'Tushar Patil'],
  'docs/08-architecture-decisions/ADR-001-deterministic-intelligence.md': ['Nikhil Salunke', 'Pranav Nandeshwar'],
  'docs/08-architecture-decisions/ADR-002-navigation-model.md': ['Aboli Mundralkar', 'Pragati Dhumal', 'Tushar Patil'],
  'docs/08-architecture-decisions/ADR-003-behavior-phase-engine.md': ['Sanskriti Choudante', 'Utkarsha Chougule'],
  'docs/08-architecture-decisions/ADR-004-separate-growth-surface.md': ['Gautami Kamath', 'Ajay Landge', 'Rohit Pandey'],
  'docs/08-architecture-decisions/ADR-005-deterministic-first-ai.md': ['Nikhil Salunke', 'Pranav Nandeshwar'],
  'docs/09-constitution-system/02-governance.md': ['Nikhil Salunke'],
  'docs/09-constitution-system/04-update-process.md': ['Nikhil Salunke'],
  'docs/09-constitution-system/12-drift-detection.md': ['Nikhil Salunke'],
};
